### ISSUE TITLE
Couldn't load plugin on Linux

### ISSUE THREAD

**Issue by raspin0** [teampanfu/panfu-desktop#1] opened 2021-07-25 13:56 UTC
![image](https://user-images.githubusercontent.com/39202451/126901708-141a3b17-e0b8-4a51-bdd4-95239920b144.png)

**Comment by teampanfu** [comment] 2021-07-26 00:22
Unfortunately, we have not yet been able to find out the reason for this. The Flash plugin is packaged and the path to it should be correct.

If someone has an idea why the plugin cannot be loaded, please open a pull request.

**Comment by teampanfu** [comment] 2021-09-03 01:40
I have now tested the application on a Debian 10 machine and found no problems. Everything works as expected.

If the problem persists, something else must be the cause. As already mentioned, the path is correct and the Flash plug-in is included in the application.

Closing this issue for now.

**Closed as completed by teampanfu** 2021-09-03 01:40 UTC
Labels: bug, help wanted

**Comment by raspin0** [comment] 2021-09-04 15:17
> I have now tested the application on a Debian 10 machine and found no problems. Everything works as expected.
> 
> If the problem persists, something else must be the cause. As already mentioned, the path is correct and the Flash plug-in is included in the application.
> 
> Closing this issue for now.

I'm on deepin(debian 10 stable) I wonder if there are maybe some dependencies I have to install?

**Comment by raspin0** [comment] 2021-09-04 15:23
nevermind. I just downloaded the latest version(1.2.2)and everything seems to be working. Thank you for the fix

**Comment by teampanfu** [comment] 2021-09-04 16:47
Nice to hear it works! I assume it was due to Chromium's sandbox being enabled.
